# Generated by Django 4.2.7 on 2024-02-20 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vacancy", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="master",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="category",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="master", to="vacancy.category"
            ),
            preserve_default=False,
        ),
    ]
