# Generated by Django 4.2.7 on 2024-02-21 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("vacancy", "0002_remove_vacancy_master_vacancy_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="parent",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="master",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, related_name="master", to="vacancy.mastertype"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="category", to="vacancy.category"
            ),
        ),
    ]
